### ISSUE TITLE
Lookup rate limiter test is flaky

### ISSUE THREAD

**Issue by mrut2pac** [mathpaquette/IQFeed.CSharpApiClient#108]
The below operations need to be atomic:
```
requests.Add(requestsCount);
Interlocked.Exchange(ref requestsCount, 0);
```
Otherwise we may get the `requestsCount` incremented in between the lines and resetting to 0 may lose some of the requests.

The quick fix could be look like:
```
var requestsCountCopy = requestsCount;
requests.Add(requestsCountCopy);
Interlocked.Add(ref requestsCount, -requestsCountCopy);
```
Something like this, IMHO, should remove the test flakiness.

**Comment by mathpaquette** [comment]
Okay good. I'm about to create a new PR to manage another issue we have.
