### ISSUE TITLE
PeriodVolume doesn't fit in 32 bit integer of IntervalMessage

### ISSUE THREAD

**Issue by samushenkov** [mathpaquette/IQFeed.CSharpApiClient#122]
Hey there.

Some 4-hour candles for C (CITIGROUP) have period volume that doesn't fit in 32 bit integer field of IntervalMessage.
This causes other various problems depending on used API method.

**Comment by mathpaquette** [comment]
@samushenkov  could you please include requests you used?

**Comment by samushenkov** [comment]
I am not sure about exact time period, so try something like this:

```
var dateFrom = new DateTime(2000, 01, 01, 0, 0, 0);
var dateTo = new DateTime(2021, 04, 22, 0, 0, 0);

var interval = 3600 * 4;

var maxDatapoints = 50000;

var candles = await lookupClient.Historical.GetHistoryIntervalTimeframeAsync("C", interval, dateFrom, dateTo, maxDatapoints: maxDatapoints, dataDirection: DataDirection.Newest, labelAtBeginning: LabelAtBeginning.Beginning);
```

**Comment by mathpaquette** [comment]
@samushenkov are you getting InvalidData or app crash ?

**Comment by samushenkov** [comment]
It depends on used api method.

Without request id:
GetHistoryIntervalTimeframeAsync throws InvalidData exception. And the next subsequent request to the same SocketClient returns candles from the first request.

With request id:
Calling GetHistoryIntervalTimeframeAsync will end in app crash. It is not possible to handle exception.

**Comment by mathpaquette** [comment]
got it thanks.

**Comment by mathpaquette** [comment]
@samushenkov  super helpful all your issues/comments

**Comment by samushenkov** [comment]
Thanks

**Comment by mathpaquette** [comment]
@samushenkov please have a look to my PR.

**Comment by mathpaquette** [comment]
@samushenkov  can you confirm its fine now.

**Comment by samushenkov** [comment]
Hey @mathpaquette, thank you for your work! I will check when have a free minute.

**Comment by mathpaquette** [comment]
@samushenkov please dont forget to star us :)
