### ISSUE TITLE
IQFeed client returns data from previous request

### ISSUE THREAD

**Issue by samushenkov** [mathpaquette/IQFeed.CSharpApiClient#124]
Subsequent requests can return not proceed messages from previous request.
This issue is caused by #122 and can be reproduced if user uses GetIntervalMessages (without RequestId) method.

TryParse returns false in case if it can't parse upcomming message.
![image](https://user-images.githubusercontent.com/11872649/115851482-aabf1600-a42f-11eb-93cf-5911f616f6c1.png)
This means that client doesn't read all messages sent by iqconnect. Next data request to the same client will consume queued (unread) data.

**Comment by mathpaquette** [comment]
@samushenkov thats indeed a very good one.
