### ISSUE TITLE
I cannot compile this code with Visual Studio 2022

### ISSUE THREAD

**Issue by CBrauer** [mathpaquette/IQFeed.CSharpApiClient#130]
Hey, 
I cannot compile this code with Visual Studio 2022.

![image](https://user-images.githubusercontent.com/1317234/127684961-62d4d76e-2066-40cb-8dda-b75f35d1c13e.png)

Any suggestions on how to fix this code will be greatly appreciated.

Charles

**Comment by NichUK** [comment]
try changing line 10 to:

    public event Action<IUpdateSummaryMessage> Level1Msg {

that seems to be what the error message is saying.

**Comment by CBrauer** [comment]
Now I get:
![image](https://user-images.githubusercontent.com/1317234/127701728-9b857488-be16-405b-999d-8c523f198df9.png)

**Comment by mathpaquette** [comment]
Did you solve it ? It's not really related to this repo though...

**Comment by mathpaquette** [comment]
@CBrauer its compiling now. Please check https://github.com/mathpaquette/IQFeed.CSharpApiClient.Samples/commit/04d173b024a3fca2d40c36afccc4042d77d1d665

Also dont forget to star the projects.

Thanks,
Math

**Comment by CBrauer** [comment]
Thanks mathpaquette, I appreciate all your hard work.
