### ISSUE TITLE
Files on disk contain "!ENDMSG!,"

### ISSUE THREAD

**Issue by veng1** [mathpaquette/IQFeed.CSharpApiClient#131]
I see no obvious way to avoid writing !ENDMSG!, other than create the file and delete the last line.

What am I missing?

Thank you.

**Comment by mathpaquette** [comment]
What are you doing more specifically?

**Comment by mathpaquette** [comment]
Please check this example. https://github.com/mathpaquette/IQFeed.CSharpApiClient/blob/master/src/IQFeed.CSharpApiClient.Examples/Examples/BasicFileHistorical/BasicFileHistoricalExample.cs#L35
