### ISSUE TITLE
Support of new IqFeed version 6.2

### ISSUE THREAD

**Issue by u1035** [mathpaquette/IQFeed.CSharpApiClient#133]
Hello!
Thank you for your work!

There is new version released September 20th, 2021 - seems like some changes needs to be made.
I got "File not found" exception somewhere inside IQFeedLauncher.Start() - but didn't investigate it deeper yet.

**Comment by mrut2pac** [comment]
64bit! - IQConnect (the main feed component) and all display apps are now 64bit.  We will no longer distribute 32bit versions of these core IQFeed components.  This also requires a change to installation practices for IQFeed so if your app is using a hard coded IQFeed path to launch the feed, this will need updating.
This should be the cause. Most likely. 

Regards,
Vardan

**Comment by mathpaquette** [comment]
duplicated #61
