### ISSUE TITLE
getting stock symbol info (industry, sector etc)

### ISSUE THREAD

**Issue by emilge** [mathpaquette/IQFeed.CSharpApiClient#138]
Guys, anyone would advise a quick way to get symbol info ?

**Comment by mathpaquette** [comment]
do you mean this file http://www.dtniq.com/product/mktsymbols_v2.zip

**Comment by emilge** [comment]
> do you mean this file http://www.dtniq.com/product/mktsymbols_v2.zip

I mean through API request )
