### ISSUE TITLE
Historical.ReqHistoryIntervalTimeframeAsync for symbol CDAX.X throws System.OverflowException

### ISSUE THREAD

**Issue by hunterfries** [mathpaquette/IQFeed.CSharpApiClient#14]
HIT request for 1/1/2007 to current throws System.OverflowException: 'Value was either too large or too small for an Int32.'

**Comment by mathpaquette** [comment]
already fixed on master, will be on the next release. Plan to release 1.4.0 tonight!

**Comment by mathpaquette** [comment]
sorry, I think the issue still there. Gonna fix it! Sorry again

**Comment by mathpaquette** [comment]
@hunterfries gimme the full command that you used? Interval needed. thanks.

**Comment by hunterfries** [comment]
lookupClient.Historical.ReqHistoryIntervalTimeframeAsync(
                               CDAX.X,
                                60,
                                startDateTime,
                                endDateTime);

startDateTime is new Datetime(2007, 1, 1)
endDateTime is DateTime.Now

**Comment by hunterfries** [comment]
Also happening with symbol EPU

**Comment by mathpaquette** [comment]
@hunterfries do you suggest both TotalVolume and PeriodVolume to be long?

**Comment by mathpaquette** [comment]
seems only problematic with the TotalVolume

**Comment by mathpaquette** [comment]
review
