### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jphiggs** [mathpaquette/IQFeed.CSharpApiClient#143]
Hi Mathieu, it's been a while.  You may recall I helped implement L2 a few years ago and was going to create an example for #141.  As I was reviewing the current examples, I found that they're blowing up on the 6.2 ProtocolVersion specified in IQFeedDefault.cs.  The AdminMessageHandler is throwing because the response string starts with 'E'.   That's as far as I got for now.  For some reason IQFeed is returning an error.  The response string is "E,6.2 is not a valid protocol.,\r"

**Comment by mathpaquette** [comment]
@jphiggs its been a while! Glad to see you again around! Are you able to dig a little bit further ? I dont have access to market depth anymore. Math

**Comment by jphiggs** [comment]
Yes I will gladly, but it's the current examples that are failing with 6.2 and I haven't looked at any of this code in a long while.  If you can't afford the time to figure out that one, maybe I'll create a new set of examples with a console menu targeting .NET 6 and also a set of the same examples for WPF .

**Comment by mathpaquette** [comment]
@jphiggs sorry ive been sick for few days. where's the PR?
