### ISSUE TITLE
The system cannot find the file specified Error

### ISSUE THREAD

**Issue by rajithchat** [mathpaquette/IQFeed.CSharpApiClient#149]
**"The system cannot find the file specified"** exception is thrown when using the IQFeed.CSharpApiClient in .NET console application. Below is the code I use. 
```
    class Program
    {
        static void Main(string[] args)
        {
            IQFeedLauncher.Start();
            var lookupClient = LookupClientFactory.CreateNew();
            lookupClient.Connect();
            var tickMessages = lookupClient.Historical.GetHistoryTickDatapointsAsync("AAPL", 100)
                .GetAwaiter().GetResult();
            foreach (var tickMessage in tickMessages)
            {
                Console.WriteLine(tickMessage.Last);
            }
            Console.ReadLine();
        }
    }
```

The exception is thrown when executing the IQFeedLauncher.Start();
app.config file is updated with below details. (values are included in original app.config file)

```
<appSettings>
    <add key="IQConnect:login" value=""/>
    <add key="IQConnect:password" value=""/>
    <add key="IQConnect:product_id" value=""/>
    <add key="IQConnect:product_version" value="6.2.0.23"/>
  </appSettings>
```
I tried the examples given [here](https://github.com/mathpaquette/IQFeed.CSharpApiClient/tree/master/src/IQFeed.CSharpApiClient.Examples). This example is also throwing the same error for me.

Windows
Visual Studio 2017/2019

Some help would be appreciated
Thanks

**Comment by BunkerCoder** [comment]
@rajithchat - It looks like the iqconnect.exe file isn't in your path.  It is usually installed in C:\Program Files\DTN\IQFeed.  Add that to your path, and you should be good-to-go.

**Comment by BunkerCoder** [comment]
@rajithchat - That's correct.  It's not specific to IQFeedCSharpApiClient; the DTN IQFeed API (iqconnect.exe) listens for socket connections on the local loopback port.  It's designed for desktop.  And I think even if you could find a way to run it from a web job, it would violate the DTN license agreement.
