### ISSUE TITLE
Historical.ReqHistoryIntervalTimeframeAsync for symbols containing ".X" returning daily data

### ISSUE THREAD

**Issue by hunterfries** [mathpaquette/IQFeed.CSharpApiClient#15]
lookupClient.Historical.ReqHistoryIntervalTimeframeAsync(
                               "NIK.X",
                                60,
                                startDateTime,
                                endDateTime)

startDateTime is new Datetime(2007, 1, 1)
endDateTime is DateTime.Now

Going to investigate this further on my own...not sure what is going on here. Requests are identical to requests that are returning correct interval data, however symbols containing ".X" are returning daily data at around the original request time.

**Comment by hunterfries** [comment]
Looks like .X symbols only have daily tick data.

**Comment by mathpaquette** [comment]
@hunterfries can you please gimme me more info on this one want to have it. dont hesitate to communicate with iqfeed support.

**Comment by hunterfries** [comment]
I closed this one...should have done my due diligence before opening. Some of the symbols are only returning daily data when requesting interval data...reaching out to iqfeed.

**Comment by mathpaquette** [comment]
Okay but I'm confused about the two recently opened...

**Comment by hunterfries** [comment]
Replied offline with more context.
