### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by openSourceBugs** [mathpaquette/IQFeed.CSharpApiClient#153]
IQFeedLauncher.Start("<user>", "<pass>", "<pid>")
{Win32Exception}Win32Exception('The system cannot find the file specified')

What makes this issue show up?  this happens after importing the IQFeed.CharpApiClient successfully using the Python .net importer.  What file is it looking for?  This error is pretty much impossible to debug from the python client.

**Comment by openSourceBugs** [comment]
Is this just an authentication error?  If so, it should throw one instead of "file not found" error.  I'm still not sure if this is the issue or if it's something else.

**Comment by openSourceBugs** [comment]
looks like this is a duplicate issue.  The other issue does not seem to be resolved either.

**Comment by mathpaquette** [comment]
@openSourceBugs how can I reproduce the issue ?
