### ISSUE TITLE
LookupClient BufferSize can be customized

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#16]
Anyhow, when i look up the Options Chain for AMZN on 20180731, this is the error i get (Just wanted to share)
 
![exception](https://user-images.githubusercontent.com/4358455/43773431-b3d0a69c-9a13-11e8-9676-e1b549849fb2.png)

**Comment by mathpaquette** [comment]
Solution: Basically what you’ll need to do, git pull, and use the LookupClientFactory.CreateNew(bufferSize: 128*1024) customized parameters and pass something larger to the default value which is 32*1024. 128*1024 should be fine.

**Comment by mathpaquette** [comment]
@license786 thank you to reporting it.

**Comment by license786** [comment]
Thank you for fixing this promptly
