### ISSUE TITLE
IntervalMessage and DailyWeeklyMonthlyMessage have Open and Close flipped

### ISSUE THREAD

**Issue by hunterfries** [mathpaquette/IQFeed.CSharpApiClient#17]
Per IQ Feed:

Response is HLOC and both message types are parsing as HLCO. Will be creating PR for fix shortly.

**Comment by mathpaquette** [comment]
I have to double check that! thanks for reporting.

**Comment by hunterfries** [comment]
PR is open for the fix.

**Comment by mathpaquette** [comment]
thank you @hunterfries for this PR :)
