### ISSUE TITLE
[MessageHandlers] Skipping Parse if related event is null

### ISSUE THREAD

**Issue by Nucs** [mathpaquette/IQFeed.CSharpApiClient#26]
Looking at `Level1MessageHandler`, every message that comes in is first parsed and only then it's related event is checked if it there is any delegates registered to it.
Skipping the parsing will actually improve performance on heavy applications.
note: this might be relevant to all message handlers.

Example for a fix:

``` C#
    private void ProcessUpdateMessage(string msg)
    {
      Action<UpdateSummaryMessage> update = this.Update; //copy locally for multithreading purposes.
      if (update == null)
        return;
      update(UpdateSummaryMessage.Parse(msg));
    }
```

@mathpaquette, Let me know if you want a PR.

**Comment by mathpaquette** [comment]
Dont see really any valid use cases. I mean, the network will be even a bigger loss than this simple parsing thing. I should unwatch symbols when no one is using the data itself.
