### ISSUE TITLE
Historical Expired Options Volume

### ISSUE THREAD

**Issue by veng1** [mathpaquette/IQFeed.CSharpApiClient#28]
Historical Options do not seem to include volume and open interest.  Can they be made available?

**Comment by mathpaquette** [comment]
Sure, you can get it using Historical Daily request.
Something like this: var dailyMessages = await lookupClient.Historical.ReqHistoryDailyDatapointsAsync("AAPL", 100);

**Comment by veng1** [comment]
Actually, I'd like it minute by minute to scan for large block trades.  That often indicates big players are taking an option position in advance of an event.

**Comment by mathpaquette** [comment]
Sure, I know what you trying to achieve but unfortunately I don’t think IQFeed is providing Open Interest other than Daily request. I’m just the owner of this library.
Please ask to support@iqfeed.net<mailto:support@iqfeed.net> and let me know if there’s another way!

Mathieu

**Comment by veng1** [comment]
Please look at: API Doc Historical via TCP/IP ->Result Format for HIX, HID, and HIT requests
Note: Total Volume and Period Volume.  They both return integers
Of course, the doc is not always correct.

I was able to retrieve this data using ver 5 protocol.  As an example, VXX1019F20_Min.csv:

Time Stamp,High,Low,Open,Close,Total Volume,Period Volume,Number of Trades
2010-05-28 12:14:00,8.50,8.50,8.50,8.50,20,20,0,
2010-05-28 12:18:00,8.50,8.50,8.50,8.50,50,30,0,
2010-05-28 12:38:00,8.70,8.70,8.70,8.70,55,5,0,
2010-05-28 12:39:00,8.70,8.70,8.70,8.70,100,45,0,
2010-05-28 13:17:00,8.60,8.60,8.60,8.60,110,10,0,
2010-06-01 14:18:00,9.20,9.10,9.20,9.10,6,6,0,
