### ISSUE TITLE
Raw.RequestHistory

### ISSUE THREAD

**Issue by veng1** [mathpaquette/IQFeed.CSharpApiClient#29]
Could the Raw.RequestHistory, which seems to be intended to create files have an option to include a header?

In the past, I've done it like this:
sRequest = String.Format("HDX,{0},{1},{2},{3},{4}\r\n", txtSymbol.Text, txtStrike.Text, txtDirection.Text,      txtRequestID.Text, txtDatapointsPerSend.Text);
header = "Time Stamp,Last,High,Low,Open,Close,Volume,Open Interest";
for each type of request.

**Comment by mathpaquette** [comment]
You need to manually happen the file and adding the header you wish to add.
