### ISSUE TITLE
Hopefully. This is so good. But I use python...

### ISSUE THREAD

**Issue by chengsu99** [mathpaquette/IQFeed.CSharpApiClient#31]

**Comment by mathpaquette** [comment]
Hey @chengsu99 thanks for contacting us. Let me check what we can offer you to leverage of this lib!

**Comment by Nucs** [comment]
And if you are still willing use in python, I would suggest [pythonnet](https://github.com/pythonnet/pythonnet/) as it works good enough.

**Comment by chengsu99** [comment]
thank you so much

**Comment by mathpaquette** [comment]
Yes, I think pythonnet or ironpython is your best bet!

**Comment by chengsu99** [comment]
> Hey @chengsu99 thanks for contacting us. Let me check what we can offer you to leverage of this lib!
seems it is for python 2.7. But I'm using python 3.6 on OSX.
