### ISSUE TITLE
CSharpApiClient sometimes binds to IPv6 instead of IPv4.

### ISSUE THREAD

**Issue by mbmurray** [mathpaquette/IQFeed.CSharpApiClient#35]
When starting up, the library can try to bind to the admin port of the client using IPv6 depending on how your network/computer is set up.  The library should be changed to filter out any IPv6 addresses.

**Comment by mathpaquette** [comment]
thanks @mbmurray ill give a look.

**Comment by mathpaquette** [comment]
https://www.nuget.org/packages/IQFeed.CSharpApiClient/1.4.3

thanks @mbmurray
