### ISSUE TITLE
Connection Lost event for streaming clients

### ISSUE THREAD

**Issue by mrut2pac** [mathpaquette/IQFeed.CSharpApiClient#39]
Would be nice to have a built in support for socket disconnected event for streaming clients so that the user will be notified when the underlying socket is closed and the updates will stop. Now until you make another request you won't know about the problem.

**Comment by Nucs** [comment]
Related: #25

**Comment by mathpaquette** [comment]
well, maybe we can create a simple watchlog for level1 quote and maybe level2. You can also check for level1 timestamp event and if you didnt receive anything, you're disconnected.

**Comment by mathpaquette** [comment]
gonna close it since this is related to the same issue.

**Comment by mrut2pac** [comment]
No problem. I have a monitor implementation that does what you described. I forked your repo, will implement additional stuff that I need, by maintaining your coding pattern. 
Later we can merge it back if you see value.
