### ISSUE TITLE
Changing Money-related variables from float to decimal.

### ISSUE THREAD

**Issue by Nucs** [mathpaquette/IQFeed.CSharpApiClient#4]
## Summary
The value type for variables that hold a balance/portfolio or price/bid/ask should be [`decimal`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/decimal).

### Pros
* High accuracy when handling calculations with money (this is `decimal`'s purpose and what it was created for).
* `decimal` is the standard value type for handling money in all libraries I've worked with by now. ([QuantConnect/Lean](https://github.com/QuantConnect/Lean), [sonvister/Binance](https://github.com/sonvister/Binance), [sefbkn/gdax.netcore](https://github.com/sefbkn/gdax.netcore))
---
### Cons
* Breaking Change that will require move to version 2.0.
* There is a performance impact when using decimal, see [reference](https://stackoverflow.com/a/34332452/1481186).
* A `Decimal `takes 16 bytes vs `Double `that takes 8 bytes. essentially doubling the memory usage.
---

My Opinion
The performance impact isn't small but tolerable.
The accuracy is indeed required.
The changes are breaking, therefore it will have to be released in a new major version release.
Unless we plan to break the market's standard by being a special snowflake, I do not see a reason.

Would love to hear your opinions.

**Comment by hunterfries** [comment]
I agree. Will save the step of converting to decimal in our client apps. Pros outweigh the cons.

**Comment by mathpaquette** [comment]
We gonna stick with float since most of the time, for example when streaming level 1 data, we dont care about handling all UpdateSummaryMessage one by one. I'll add a special extension method for those of you want to go with decimals.

**Comment by mathpaquette** [comment]
@Nucs @hunterfries @jphiggs @mrut2pac thinking about changing from float to double

**Comment by mathpaquette** [comment]
just realized some edge cases like  Berkshire Hathaway Inc. with a price of 313,270.00 so this is already the limit of 7 digits for a float.

Do we really need decimal ? I dont think so

**Comment by mathpaquette** [comment]
@Nucs float is actually 4 Bytes compare to 16 Bytes for a decimal. The thing is all our messages are immutable you ill never apply addition or other mathematical operators.

**Comment by mathpaquette** [comment]
@Nucs okay you were right I think. Lets aim for the standard decimal.... Im going to release that in v2 with Market Depth support :)

**Comment by Nucs** [comment]
I mean real high-frequency trading systems are written in C++, no-one should use C# for that kind of trading (performance-wise). So perf-wise moving to decimal is alright.
>with a price of 313,270.00 so this is already exceeding the limit of 7 digits for a float.

I don't think the 7 digits refer to the real number but to the fraction precision. The range is huge.

![image](https://user-images.githubusercontent.com/649919/67155752-8277c800-f31d-11e9-93a5-b881b6e9dd0c.png)

**Comment by mathpaquette** [comment]
@Nucs my concern is mainly memory-wise not much performance. In my previous app, I needed to store in memory a bunch of Intervals data to perform calculation on the fly. Lets say the footprint was about 1.5Go now for the same thing it will be about 4 times the size without much additional value rather making sure that some edge cases like Berkshire can handle.

**Comment by Nucs** [comment]
@mathpaquette How about producing two nuget packages. One that uses decimal and an other float.
The user can choose if he prefers compatibility with external libraries and precision or lower memory usage.
Add a definition FLOAT or DECIMAL to two separate build configuration (similarly to Debug and Release modes)

```C#
//at the top of the file
#if FLOAT
using valuetype = System.Single;
#elif DECIMAL
using valuetype = System.Decimal;
#endif

//use valuetype instead of float or double
valuetype somefunction();
```

**Comment by mathpaquette** [comment]
@Nucs could be but seems a little bit overkill :)
What about replacing all float to double and providing ToDecimal for each messages ?
Even SciChart doesnt support decimals if I'm not wrong.

**Comment by Nucs** [comment]
>  could be but seems a little bit overkill :)

Literally 10 minutes to set up projects and buildbot and another 15 refactoring.

**Comment by mathpaquette** [comment]
> > could be but seems a little bit overkill :)
> 
> Literally 10 minutes to set up projects and buildbot and another 15 minutes refactoring.
> You solve it how ever you like, I would do that this way.

Not overkill in a sense to setup but I never experienced that kind of duality for any libs I used in the past in C# which usability its a bad sign that kind of uniqueness if you know what I mean.

**Comment by mathpaquette** [comment]
> > could be but seems a little bit overkill :)
> 
> Literally 10 minutes to set up projects and buildbot and another 15 minutes refactoring.
> You solve it how ever you like, I would do that this way.

We are just discussion right now, I'm open-minded to what people are saying.

**Comment by mrut2pac** [comment]
I like the idea of having both float and decimal.

**Comment by mathpaquette** [comment]
Same, the design is so flexible we can support it easily. Just boilerplate code to add... I think at the factory level will be the best...

On Oct 20, 2019, at 9:32 PM, mrut2pac <notifications@github.com> wrote:

﻿

I like the idea of having both float and decimal.

**Comment by mathpaquette** [comment]
took some time but finally supporting float, double and decimal out of the box.

**Comment by mathpaquette** [comment]
Version 3 will drop support for generic message handlers meaning doubles will become default across the library no matter what for simplicity and performance reasons.
