### ISSUE TITLE
In my error list

### ISSUE THREAD

**Issue by MerlinBrasil** [mathpaquette/IQFeed.CSharpApiClient#40]
Hi & thanks for all your hard work!

I'm using VS 2017 and, on first compile I get the one and only message:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU5125	The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.	IQFeed.CSharpApiClient	C:\Program Files\dotnet\sdk\2.1.507\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	202	

Only a warning. Obviously not a huge deal, but thought I'd mention it

Best regards,
Merlin
MerlinBrasil@gmail.com

**Comment by mathpaquette** [comment]
@MerlinBrasil thanks for reporting this. Ill take a look.

**Comment by mathpaquette** [comment]
I'm using VS 2017 updated to the latest version and didnt have any error. Are you sure its 2017 or maybe 2019?

**Comment by MerlinBrasil** [comment]
I'm using what you're using. 2017 updated to the latest version.

Best,
Merlin

**Comment by mathpaquette** [comment]
Could you please include a screenshot ? thanks

**Comment by MerlinBrasil** [comment]
I did a cut and paste of the error in my initial message in this thread

**Comment by mathpaquette** [comment]
Thanks
