### ISSUE TITLE
Update interval doesn't work for DerivativeClient.ReqBarWatch

### ISSUE THREAD

**Issue by PaulGlynn588** [mathpaquette/IQFeed.CSharpApiClient#41]
You can request say 1 minute bars that are updated every 5 seconds. Currently it just ignores the update interval of 5 seconds.

The request is incorrectly formatted in DerivativeRequestFormatter.ReqBarWatch. The developer documentation says the format should be:

BW,[Symbol],[Interval],[BeginDate BeginTime],[MaxDaysOfDatapoints],[MaxDatapoints],[BeginFilterTime],[EndFilterTime],[RequestID],[Interval Type],[Reserved],[UpdateInterval]

The reserved field is not taken into account, so it should be:

`$"BW,{symbol.ToUpper()},{interval},{beginDate?.ToString(DerivativeDatetimeFormat)},{maxDaysOfDatapoints},{maxDatapoints},{beginFilterTime?.ToString(DerivativeTimeFormat)},{endFilterTime?.ToString(DerivativeTimeFormat)},{requestId},{intervalType?.ToString().ToLower()},,{updateInterval}{IQFeedDefault.ProtocolTerminatingCharacters}";`

Also there shouldn't be a comma before "{IQFeedDefault.ProtocolTerminatingCharacters}" for all the request types in DerivativeRequestFormatter.

**Comment by mathpaquette** [comment]
Thanks for reporting this! Ill give a look and fix this today!

Mathieu

**Comment by mathpaquette** [comment]
@PaulGlynn588 please review PR
