### ISSUE TITLE
Level1 snapshot methods will stop current watches on same symbols

### ISSUE THREAD

**Issue by mrut2pac** [mathpaquette/IQFeed.CSharpApiClient#44]
Not sure if that is the expected behavior, but if you call any of these snapshot methods:
- GetFundamentalSnapshotAsync
- GetUpdateSummarySnapshotAsync

on a client while there was an ongoing **ReqWatch** on the same symbol, the updates will stop since both of them are calling **ReqUnwatch** on completion. 

From the user perspective I didn't expect that. I though I'd report it here, FYI.

**Comment by mathpaquette** [comment]
@mrut2pac thanks for contacting us ! Yes, I agree with you from the client perspective, this is not something expected. We should have a shared count and only unsubscribe if the count equals 1. What do you think?

**Comment by mrut2pac** [comment]
Yeah, makes sense.

**Comment by mathpaquette** [comment]
@mrut2pac what do you of instead of writing additional logic to handle that, Im suggesting to users to use a new Level1 client which cannot unsubscribe already streaming symbols.

**Comment by mrut2pac** [comment]
In my code I have another layer that maintains subscriptions. When Fundamental or Quote snapshots are requested I return it if the subscription already exists otherwise I create a new one that gets expired after a configured timeout. Your suggestion sounds like a good workaround, but not a nice long term solution. Let's think about it a bit more. I will post if I have any ideas.
