### ISSUE TITLE
create a Docker image to be able to run Integration Tests when creating a PR

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#48]

**Comment by mathpaquette** [comment]
anyone interested ?

**Comment by flerka** [comment]
@mathpaquette Hi! I'm interested, from what I've understood it must be multistage dockerfile with 1st stage that copies and complies integration test project and second stage that runs integration test using that compiled code?

**Comment by mathpaquette** [comment]
Hello @flerka thank you for your interest! The issue right now, we can only run unit tests because integration tests require [IQFEED CLIENT](http://www.iqfeed.net/index.cfm?displayaction=support&section=download) to be installed on the Continuous Integration server. I think it would be possible to create a Docker file that will pull IQFeed Client and integration tests will be executed in it. I think the first step will be to check if AppVeyor is supporting such setup.

**Comment by hfries** [comment]
@mathpaquette do you have a preferred method of storing / injecting creds to run the integration tests? I have the dockerfile built, but NotSupportedException being thrown when running tests against netcore 2.0. I'll put up a pr for review / discussion later this week.

**Comment by mathpaquette** [comment]
@hfries afterthought this might be more cumbersome than very helpful. Do you plan to use it in any ways?

**Comment by hunterfries** [comment]
@mathpaquette I'm game to put something up if anyone sees value in it. I don't think I would use it since my dev env would have iq connect installed, but if we wanted to ensure some level of consistency to the tests, containerizing the tests would check the box.
