### ISSUE TITLE
Downgrade/Support .net-framework version from .net462 to .net45.

### ISSUE THREAD

**Issue by Nucs** [mathpaquette/IQFeed.CSharpApiClient#5]
As a library, `.net-framework` version should be supported at lowest version possible.
Therefore `.net-framework` version should be downgraded or even better also support `.net45`,
Below `.net45` there will be needed heavier changes related to [`TPL`](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl) and `Tasks`.

In `.net45` there is no `System.Configuration.ConfigurationManager`, 
Use mscorlib's assembly `System.Configuration` instead.

**Comment by Nucs** [comment]
I've already added support for `.net45` it in my local private fork.
Assign it to me and I'll add a pull request.

**Comment by mathpaquette** [comment]
@Nucs after this one, I can release 1.3.1
