### ISSUE TITLE
Add news support

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#51]

**Comment by mathpaquette** [comment]
@mrut2pac interested in it?

**Comment by jduke99** [comment]
Any progress on the News Example?  eg getting historical news or streaming news

**Comment by mathpaquette** [comment]
I can manage that next week.

**Comment by mathpaquette** [comment]
if you star the project :P

**Comment by mathpaquette** [comment]
@jduke99 Dont forget to star the project. Example in c# for Python?

**Comment by jduke99** [comment]
@mathpaquette  C# please

**Comment by mathpaquette** [comment]
@jduke99 added support for news! please review https://github.com/mathpaquette/IQFeed.CSharpApiClient/blob/master/src/IQFeed.CSharpApiClient.Tests.Integration/Lookup/News/NewsFacadeTests.cs for some example!

**Comment by jduke99** [comment]
Thank you @mathpaquette .  All the tests seem to be running fine.  Being honest, even looking at the facade test, i'm still not able to build my Example.cs to quite work properly with symbols and dates.  Can you provide a call example with multiple symbols and dates for eg. 

`var newsMessages = await lookupClient.News.GetNewsHeadlinesAsync(<WHAT GOES HERE?>)`

**Comment by jduke99** [comment]
I seem to get a cannot convert string to string[] error when i try to put in an array of symbols.  i am not a c# guru, apologies if this should be obvious.

**Comment by mathpaquette** [comment]
Hi Jon,

Could you please be more precise in what you trying to achieve. Ill try to help you with that.

Thanks,
Mathieu

**Comment by jduke99** [comment]
Thanks so much.  An example would just be pulling news stories on AAPL from 2/1/2020 to 4/1/2020.

ps. I was wondering if  your offer to make a python example is still available?  In particular looking for pull as above as well as streaming level 1 news example in python.
