### ISSUE TITLE
Add unit test cases for SplitFeedMessage(this string s, int expectedParts) extension method

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#52]

**Comment by mrut2pac** [comment]
I will work on them when I have time. Sorry a bit overloaded lately.

**Comment by mathpaquette** [comment]
@mrut2pac could you please close that one? you're help much appreciated to stay this project afloat. thank you!

**Comment by hunterfries** [comment]
@mathpaquette I can put some tests up for this this weekend.

**Comment by mathpaquette** [comment]
@hunterfries if you can close this one will be nice.

**Comment by mathpaquette** [comment]
thanks @hunterfries
