### ISSUE TITLE
TestDataTests.cs failing

### ISSUE THREAD

**Issue by BunkerCoder** [mathpaquette/IQFeed.CSharpApiClient#72]
Looks like it is using lookup client instead of level1 client.
FROM CLIENT	LookupRequest	15136	1	2020-06-05 12:42:05	HTT,NEPT,20200401 040000,20200403 200000,,,,0,,

TO CLIENT	LookupError	15136	1	2020-06-05 12:42:05	E,!NO_DATA!,,

**Comment by BunkerCoder** [comment]
Sorry...my IQFeed installation was damaged. Needed to re-install it.  Test ran fine after that.
I mistakenly thought this was the wrong client port because I saw:
Connect to IQConnect by following the instructions for Level 1 via TCP/IP.
I missed the next line:
Once a connection has been established, connect to the Lookup port for IQFeed's IQConnect

**Comment by mathpaquette** [comment]
np things happen
