### ISSUE TITLE
Culture-specific parsing.

### ISSUE THREAD

**Issue by Nucs** [mathpaquette/IQFeed.CSharpApiClient#9]
During publishing my app in a virtual server that is located in France, it failed during parsing `TickMessage` at the following commented line/s:
```C#
public static TickMessage CreateTickMessage(string[] values) {
    return new TickMessage(
        DateTime.Parse(values[0]),
        float.Parse(values[1]),
        int.Parse(values[2]),
        int.Parse(values[3]),
        float.Parse(values[4]), //this line threw FormatException: Input string was not in a correct format.
        float.Parse(values[5]),
        long.Parse(values[6]),
        char.Parse(values[7]),
        int.Parse(values[8]),
        values[9]);
}
```
It happened because the machine's system language is french therefore the culture in the code is `fr-FR`
and some European countries write fraction number with comma instead of period so that line tries to parse "14,5" where in fact the value is "14.5".

Fixing it possible by specifying invariant culture like this in any line that uses `Parse`.
```C#
float.Parse(values[4], CultureInfo.InvariantCulture)
```

Edit:
The exception is thrown in any kind of parse, even in `DateTime` .

**Comment by mathpaquette** [comment]
@Nucs, very good point. I think Ill need to add the correct string pattern to parse the DateTime.
